### ISSUE TITLE
Rename to `verademo-netframework`

### ISSUE THREAD

**Issue by relaxnow** [veracode/verademo-dotnet#3]
Make it clear that this is for .NET Framework, not .NET 6+.

**Comment by relaxnow** [comment]
@tjarrettveracode I appear to not have admin rights on this repo, could you do this?

**Comment by relaxnow** [comment]
@tjarrettveracode ?

**Comment by tjarrettveracode** [comment]
Sorry, just seeing this. yes, will do.

**Comment by tjarrettveracode** [comment]
Renamed repo and updated README

**Comment by relaxnow** [comment]
Awesome, thank you @tjarrettveracode !
